### ISSUE TITLE
It just plain doesn't work

### ISSUE THREAD

**Issue by rspeed** [gregsadetsky/chrome-dont-add-custom-search-engines#1]
I've made a fork and tried to get it going again, but it appears that even if you remove the opensearch link elements, the search engine still gets added to Chrome. There might be some other completely different tactic which would work, but I'm not familiar enough with the Chrome extension API to think of one.

**Comment by rspeed** [comment]
In the meantime, you should probably remove it from the Chrome Web Store.

**Comment by then2s** [comment]
doesnt work for me as well. )=

**Comment by gregsadetsky** [comment]
Would you mind telling me for which sites the extension did not work? Thanks!

**Comment by then2s** [comment]
tested on github.com right after I installed it.

**Comment by snowbound** [comment]
Bleepingcomputer.com. You search for anything on that site and you wind up with an entry in Goiogle Chrome.

**Comment by Songworks** [comment]
I've been testing PR #2 to see if it helps. it doesn't but does make the current implementation more robust.

While testing I realized some sites like Amazon don't seem to use the expected [application/opensearchdescription+xml][1] link. Such a link-tag however is what the extension looks for and attempts to disable.
Perhaps Amazon tells Chrome through another way where to find its search engine?

[1]: http://www.opensearch.org/Specifications/OpenSearch/1.1#Type

**Comment by panozzaj** [comment]
Dropping in some notes as I was looking through what those other sites may be using.

It looks like Chrome might be looking at [form inputs that have a certain name/type convention](https://martin-thoma.com/search-engine-autodiscovery/). This looks like the case on the bleepingcomputer.com site.

Also, there is [apparently a way to trigger this using JavaScript](http://www.opensearch.org/Documentation/Developer_best_practices_guide). 

https://www.chromium.org/tab-to-search provides some general information on how Chromium handles these, and there is a `<Url` with `rel="suggestions"` approach?

These didn't seem to easily answer why Amazon was doing this. Maybe they are calling `window.external.AddSearchProvider(...)` somewhere? I tried stubbing out that function in the JavaScript console but it didn't seem to fix the problem. Could be using a different method or that hack might not be doing what I intended since it is probably meant to be a Chrome built-in method.

I think PR #2 is a step in the right direction. Hoping these breadcrumbs are helpful.

**Comment by cxw42** [comment]
@gregsadetsky Would you mind if I added my fork (referenced in #2) to the Chrome Web Store as a separate extension, and mentioned it in a comment on your extension?  I would rather not split the project and the user base, but I would like to give folks an alternative to the low reviews they are currently leaving.  Any and all comments welcome.  Thanks!

**Comment by gregsadetsky** [comment]
hey -- my great big thanks to you and everyone involved in improving this extension. I am extremely not happy at myself for abandoning this.

if you don't mind, I'd love a few extra days of your (already stretch) patience for me to look into everything, and then we could merge the fork into the main extension and release that? I'd definitely love for everyone to have access to the improved code.

thanks again & sorry again & more news soon. if you don't hear from me again, feel free to release a "competitor" extension and use a high resolution photo of me with a big red circle around it as the icon ;-) that should teach me :-) cheers

**Comment by cxw42** [comment]
@gregsadetsky Thanks for the quick reply!  I will await your comments.  For your convenience (and everybody else's), I have opened #6.

In the mean time, everybody else on this thread, hammer on #6 and let me know what doesn't work!
