### ISSUE TITLE
sites that slip through and whose search engines are added

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/chrome-dont-add-custom-search-engines#9]
- kijiji.ca (after submitting the search form)

**Comment by cxw42** [comment]
@gregsadetsky Is this issue going to hold the master list referenced in #7?  If so, may I suggest a wiki page instead?  In an issue, commenters can only edit their own comments, and it will be harder to pull the data for automated testing.

All that said, we've seen issues on:
 - bleepingcomputer.com (has two search boxes; both should be spoiled)
 - gcmap.com
 - pouet.net (because `action="search.php"` in the HTML, so it doesn't match the selector)
 - en.cppreference.com
 - perldoc.perl.org

**Comment by cxw42** [comment]
... Although, now that I think about it, if folks post live links, and all we care about in testing is that _at least one_ form on the linked page is spoiled, we could scrape this just as well as we could scrape links off a wiki page.  We just wouldn't be able to easily delete the links later if the sites changed how they searched.

In a wiki, we could have a table with URL and expected number of results (e.g., pouet 1; bleepingcomputer 2).  We could scrape the table and check for that number.  Anyway, let me know what you think.

**Comment by gregsadetsky** [comment]
great thoughts & wiki. basing off the automated testing on the wiki links is a really great one, but I'd be concerned that opening up the wiki to anyone & using those urls for testing could spell trouble. but we're not there yet. definitely let's do wiki! I'll create the page, move the links here (thank you!) there and then close this issue.

**Comment by gregsadetsky** [comment]
https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines/wiki/Sites-known-to-be-added-as-custom-search-engines
